// Generates testdata/quantities.json: the reference conversion of Kubernetes resource
// quantities, produced by apimachinery itself. bridge/snapshot.py must match it exactly,
// including the rounding, which is towards +infinity and not truncation.
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"k8s.io/apimachinery/pkg/api/resource"
)

type entry struct {
	Text     string `json:"text"`
	MilliCPU int64  `json:"millicpu"`
	Bytes    int64  `json:"bytes"`
	Note     string `json:"note,omitempty"`
}

func main() {
	cases := []struct{ text, note string }{
		{"0", "zero"},
		{"2", "whole cores"},
		{"1500m", "millicores"},
		{"500u", "microcores, rounded up to 1 millicore"},
		{"1n", "one nanocore still costs a whole millicore"},
		{"123456789n", "nanocores, as the metrics API reports CPU"},
		{"999999999n", "just under one core"},
		{"1234567890123n", "more than one core, in nanocores"},
		{"1e3", "decimal exponent form"},
		{"1500e-3", "negative exponent"},
		{"64Mi", "binary memory suffix"},
		{"8Gi", ""},
		{"1000Ki", "as the metrics API reports memory"},
		{"1G", "decimal memory suffix"},
		{"1024", "plain bytes"},
	}
	out := make([]entry, 0, len(cases))
	for _, item := range cases {
		q := resource.MustParse(item.text)
		out = append(out, entry{Text: item.text, MilliCPU: q.MilliValue(), Bytes: q.Value(), Note: item.note})
	}
	document := map[string]any{
		"comment": "Reference conversions from k8s.io/apimachinery/pkg/api/resource, generated by plugin/hack/qcheck. Both integrations must agree with these, rounding included: Kubernetes rounds towards +infinity, so 123456789n is 124 millicores, not 123.",
		"cases":   out,
	}
	encoded, err := json.MarshalIndent(document, "", "  ")
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("../testdata/quantities.json", append(encoded, '\n'), 0o644); err != nil {
		panic(err)
	}
	fmt.Println("wrote testdata/quantities.json:", len(out), "cases")
}
